Function New-PodeWebCardAddHostAddresses {
    New-PodeWebCard -Name "Add Host Addresses" -Content @(
        New-PodeWebTextbox -DisplayName "Chassis Serial Number" -Name "ChassisSerial" -PrependIcon "barcode" -Placeholder "ABC123456789"
        New-PodeWebTextbox -DisplayName "MAC Address" -Name "MacAddress" -PrependIcon "ethernet" -Placeholder "00:1A:2B:3C:4D:5E"
        New-PodeWebTextbox -DisplayName "IPv4 Address" -Name "IPv4Address" -PrependIcon "ip-network-outline" -Placeholder "192.168.1.1"
        New-PodeWebTextbox -DisplayName "IPv4 CIDR" -Name "IPv4CIDR" -PrependIcon "server-network" -Placeholder "192.168.1.0/24"
        New-PodeWebTextbox -DisplayName "WINS/Hostname" -Name "HOSTNAME" -PrependIcon "monitor" -Placeholder "my-computer"
        New-PodeWebTextbox -DisplayName "FQDN (Fully Qualified Domain Name)" -Name "FQDN" -PrependIcon "cloud-outline" -Placeholder "server.example.com"
        # New-PodeWebTextbox -DisplayName "IPv6 Address" -Name "IPv6Address" -PrependIcon "ip-network" -Placeholder "2001:db8::1"
        # New-PodeWebTextbox -DisplayName "IPv6 CIDR" -Name "IPv6CIDR" -PrependIcon "file-document-outline" -Placeholder "2001:db8::/32"
        # New-PodeWebTextbox -DisplayName "DUID (DHCP Unique Identifier - IPv6)" -Name "DUID" -PrependIcon "router-network" -Placeholder "00:03:00:01:aa:bb:cc:dd:ee:ff"
        # New-PodeWebTextbox -DisplayName "EUI-64 (Extended Unique Identifier - IPv6/IEEE 802)" -Name "EUI64" -PrependIcon "chip" -Placeholder "00-1A-2B-FF-FE-3C-4D-5E"
        # New-PodeWebTextbox -DisplayName "Bluetooth Device Address (BD_ADDR)" -Name "BD_ADDR" -PrependIcon "bluetooth" -Placeholder "00:1B:44:11:3A:B7"
        New-PodeWebTextbox -DisplayName "iSCSI Qualified Name (IQN)" -Name "IQN" -PrependIcon "harddisk" -Placeholder "iqn.1991-05.com.example:storage.disk1"
        # New-PodeWebTextbox -DisplayName "WWN (World Wide Name - Fibre Channel)" -Name "WWN" -PrependIcon "link-variant" -Placeholder "50:0a:09:81:02:3b:8c:7d"
        # New-PodeWebTextbox -DisplayName "UUID (Universally Unique Identifier)" -Name "UUID" -PrependIcon "fingerprint" -Placeholder "550e8400-e29b-41d4-a716-446655440000"
        # New-PodeWebTextbox -DisplayName "GUID (Globally Unique Identifier)" -Name "GUID" -PrependIcon "key-variant" -Placeholder "3F2504E0-4F89-41D3-9A0C-0305E82C3301"
        # New-PodeWebTextbox -DisplayName "NAA (Network Address Authority - Storage)" -Name "NAA" -PrependIcon "database" -Placeholder "0x5000A72030098A27"
        # New-PodeWebTextbox -DisplayName "IMSI (International Mobile Subscriber Identity)" -Name "IMSI" -PrependIcon "cellphone-wireless" -Placeholder "310150123456789"
        # New-PodeWebTextbox -DisplayName "IMEI (International Mobile Equipment Identity)" -Name "IMEI" -PrependIcon "cellphone-settings" -Placeholder "356938035643809"
        # New-PodeWebTextbox -DisplayName "UPN (User Principal Name - Active Directory)" -Name "UPN" -PrependIcon "account" -Placeholder "user@example.com"
        # New-PodeWebTextbox -DisplayName "URN (Uniform Resource Name)" -Name "URN" -PrependIcon "link" -Placeholder "urn:isbn:0451450523"
        # New-PodeWebTextbox -DisplayName "ORCID (Open Researcher and Contributor ID)" -Name "ORCID" -PrependIcon "book-account" -Placeholder "0000-0002-1825-0097"
        # New-PodeWebTextbox -DisplayName "DUNS (Data Universal Numbering System - Business)" -Name "DUNS" -PrependIcon "domain" -Placeholder "123456789"
        # New-PodeWebTextbox -DisplayName "ARIN Handle (American Registry for Internet Numbers)" -Name "ARINHandle" -PrependIcon "web" -Placeholder "JDOE-ARIN"
        # New-PodeWebTextbox -DisplayName "Grid ID (Global Research Identifier Database)" -Name "GridID" -PrependIcon "database-outline" -Placeholder "grid.12345.67"
        # New-PodeWebTextbox -DisplayName "PURL (Persistent Uniform Resource Locator)" -Name "PURL" -PrependIcon "link-box" -Placeholder "http://purl.org/example/resource"
        # New-PodeWebTextbox -DisplayName "EAN (European Article Number)" -Name "EAN" -PrependIcon "barcode-scan" -Placeholder "4006381333931"
        # New-PodeWebTextbox -DisplayName "ISIN (International Securities Identification Number)" -Name "ISIN" -PrependIcon "finance" -Placeholder "US0378331005"
        # New-PodeWebTextbox -DisplayName "LEI (Legal Entity Identifier)" -Name "LEI" -PrependIcon "domain" -Placeholder "54930084UKLVMY22DS16"
        # New-PodeWebTextbox -DisplayName "GS1 GIAI (Global Individual Asset Identifier)" -Name "GS1GIAI" -PrependIcon "package-variant" -Placeholder "123456789012345678"
        # New-PodeWebTextbox -DisplayName "GS1 GSRN (Global Service Relation Number)" -Name "GS1GSRN" -PrependIcon "account-supervisor" -Placeholder "1234567890123"
        # New-PodeWebTextbox -DisplayName "GS1 SSCC (Serial Shipping Container Code)" -Name "GS1SSCC" -PrependIcon "truck-delivery" -Placeholder "123456789012345678"
        # New-PodeWebTextbox -DisplayName "GS1 GTIN (Global Trade Item Number)" -Name "GS1GTIN" -PrependIcon "barcode" -Placeholder "0123456789012"
        # New-PodeWebTextbox -DisplayName "GLN (Global Location Number)" -Name "GLN" -PrependIcon "map-marker" -Placeholder "1234567890123"
        # New-PodeWebTextbox -DisplayName "DID (Decentralized Identifier)" -Name "DID" -PrependIcon "lock-outline" -Placeholder "did:example:123456789abcdefghi"
        # New-PodeWebTextbox -DisplayName "XRI (Extensible Resource Identifier)" -Name "XRI" -PrependIcon "xml" -Placeholder "xri://@example*resource"
        # New-PodeWebTextbox -DisplayName "SHA-1 Hash Fingerprint" -Name "SHA1" -PrependIcon "fingerprint" -Placeholder "3f786850e387550fdab836ed7e6dc881de23001b"
        # New-PodeWebTextbox -DisplayName "SHA-256 Hash Fingerprint" -Name "SHA256" -PrependIcon "fingerprint" -Placeholder "d2d2d0d0c4e8b1641e379f9a437ea702f7a6d3b4f658c3f4a49b6c6d73cb49fd"
        # New-PodeWebTextbox -DisplayName "PGP Key Fingerprint" -Name "PGPFingerprint" -PrependIcon "key" -Placeholder "6F3F6C89DDF1F32A3EEC53E5A1C47C6C982DF1E9"
        # New-PodeWebTextbox -DisplayName "SPKI (Subject Public Key Info) Fingerprint" -Name "SPKIFingerprint" -PrependIcon "certificate" -Placeholder "sha256-base64:abcdef1234567890abcdef1234567890abcdef1234567890"
    )
}
